#spring.application.name=campusconnect

spring.application.name=campusconnect

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect
spring.datasource.username=root
spring.datasource.password=acpt

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=campusconnectuseverify@gmail.com
spring.mail.password=gmsb lsdt tukw vmwt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


cloudinary.cloud-name=dr3z1a9fv
cloudinary.api-key=156242811591645
cloudinary.api-secret=fZAEPtECz1zttlMFZ5ed5qF3K3I

#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB